version: '2'
services:
  wildfly:
    build: images/wildfly
    ports:
     - "8080:8080"
     - "9990:9990"
    links:
      - mysql:db
  mysql:
    build: images/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "3306:3306"
  phpmyadmin:
    build: images/phpmyadmin
    environment:
      - MYSQL_ROOT_PASSWORD=toor
    ports:
      - "6060:80"
    links:
      - mysql:db